name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  Android:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        react-native-version: ['0.70.1']
        variant: ['debug']
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Create React Native app
        run: npx react-native init MyApp --version ${{ matrix.react-native-version }} --template react-native-template-typescript --skip-install

      - name: Add Yarn dependencies
        run: ./AddYarnDependencies.sh

      - name: Add Yarn scripts
        run: node ./AddYarnScripts.js

      - name: Install node_modules
        working-directory: MyApp
        run: yarn

      - name: Copy app from template
        run: ./CopyAppFromTemplate.sh

      - name: Lint with Prettier
        working-directory: MyApp
        run: yarn lint:prettier

      - name: Lint with ESLint
        working-directory: MyApp
        run: yarn lint:eslint

      - name: Check types
        working-directory: MyApp
        run: yarn types:check

      - name: Launch Metro bundler
        if: ${{ matrix.variant == 'debug' }}
        run: yarn start &
