name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  iOS:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        react-native-version: ['0.71.1']
        architecture: ['Paper', 'Fabric']
        runtime: ['JSC', 'Hermes']
        mode: ['debug', 'release']
        # exclude:
        #   - react-native-version: '0.68.4'
        #     architecture: 'Fabric'
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Write config
        run: |
          export E2E_REACT_NATIVE_VERSION=${{ matrix.react-native-version }}
          export E2E_ARCHITECTURE=${{ matrix.architecture }}
          export E2E_RUNTIME=${{ matrix.runtime }}
          export E2E_MODE=${{ matrix.mode }}
          export E2E_PLATFORM=iOS

      - name: Validate config
        run: ./ValidateConfig.sh

      - name: Create React Native app
        run: ./CreateApp.sh

      - name: Edit package.json
        run: ./EditPackageJson.sh

      - name: Install Yarn dependencies
        run: ./InstallYarnDependencies.sh

      - name: Lint with Prettier
        run: ./LintWithPrettier.sh

      - name: Lint with ESLint
        run: ./LintWithESLint.sh

      - name: Check types
        run: ./CheckTypes.sh

      - name: Install Pods
        run: ./InstallPods.sh

      - name: Launch Metro bundler
        run: ./LaunchMetroBundler.sh

      - name: Launch Appium server
        run: ./LaunchAppiumServer.sh

      - name: Build app
        run: ./BuildApp.sh

      - name: Install WebDriverAgentRunner
        run: ./InstallWebDriverAgentRunner.sh

      - name: Run E2E tests
        run: ./RunTests.sh
