name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  iOS:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        react-native-version: ['0.71.1']
        architecture: ['Paper', 'Fabric']
        runtime: ['JSC', 'Hermes']
        mode: ['debug', 'release']
        # exclude:
        #   - react-native-version: '0.68.4'
        #     architecture: 'Fabric'
    env:
      E2E_REACT_NATIVE_VERSION: ${{ matrix.react-native-version }}
      E2E_ARCHITECTURE: ${{ matrix.architecture }}
      E2E_RUNTIME: ${{ matrix.runtime }}
      E2E_MODE: ${{ matrix.mode }}
      E2E_PLATFORM: iOS
      E2E_IOS_SIMULATOR_NAME: iPhone 14 Pro
      E2E_IOS_SIMULATOR_VERSION: 16.2
      E2E_APP_NAME: MyApp
      E2E_APP_PATH: ${{ github.workspace }}/MyApp
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Validate config
        run: ./cli/ValidateConfig.sh

      - name: Create React Native app
        run: ./cli/CreateApp.sh
        timeout-minutes: 5

      - name: Copy app files
        run: ./cli/CopyAppFiles.sh

      - name: Edit package.json
        run: ./cli/EditPackageJson.sh

      - name: Install Yarn dependencies
        run: ./cli/InstallYarnDependencies.sh
        timeout-minutes: 10

      - name: Lint with Prettier
        run: ./cli/LintWithPrettier.sh

      - name: Lint with ESLint
        run: ./cli/LintWithESLint.sh

      - name: Check types
        run: ./cli/CheckTypes.sh

      - name: Install Pods
        run: ./cli/InstallPods.sh
        timeout-minutes: 15

      - name: Launch Metro bundler
        run: ./cli/LaunchMetroBundler.sh

      - name: Launch Appium server
        run: ./cli/LaunchAppiumServer.sh

      - name: Build app
        run: ./cli/BuildApp.sh
        timeout-minutes: 60

      - name: Install WebDriverAgentRunner
        run: ./cli/InstallWebDriverAgentRunner.sh

      - name: Run E2E tests
        run: ./cli/RunTests.sh
        timeout-minutes: 15
